# Generated by Django 5.1.5 on 2025-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
