# Generated by Django 5.1.5 on 2025-03-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_imageblock_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageblock',
            old_name='image_order',
            new_name='block_order',
        ),
    ]
