# Generated by Django 5.1.5 on 2025-03-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_image_order_imageblock_block_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='block_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок блока'),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
        ),
    ]
